myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home_index, name='index'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('charts/', views.charts_view, name='charts'),
    path('tables/', views.tables_view, name='tables'),
    path('insert/', views.insert, name='insert'),
    
    path('create_company/', views.create_company, name='create_company'),

    path('create_product/', views.create_product, name='create_product'),
    
    path('create_sales/', views.create_sales, name='create_sales'),

    # path('create_stores/', views.create_stores, name='create_stores'),

]

salesanalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True, default="default@example.com")
    location = models.CharField(max_length=255)
    description = models.TextField()
    img = models.ImageField(upload_to='images/CustomerProfilePic/', null=True, blank=True)
    password = models.CharField(max_length=255)
     # Add a OneToOneField to associate a Client with a User
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')


class Company(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    img = models.ImageField(upload_to='images/ProductPic/', null=True, blank=True)
    quantity = models.IntegerField(default=0)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)

class Client_Product_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Sales(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(auto_now_add=True)
    amount = models.IntegerField(default=0)
    totalprice = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_indivisual = models.BooleanField(default=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)


class Client_Sales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    s_id = models.ForeignKey(Sales, on_delete=models.CASCADE)

class TotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)

class Client_TotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    ts_id = models.ForeignKey(TotalSales, on_delete=models.CASCADE)

class DateTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_DateTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(DateTotalSales, on_delete=models.CASCADE)

class ProductTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_ProductTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(ProductTotalSales, on_delete=models.CASCADE)

class DateProductTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_DateProductTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(DateProductTotalSales, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Company, Product, Sales, Client

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'quantity', 'c_id', 'img']



class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        fields = ['amount', 'is_indivisual', 'p_id', 'totalprice']

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'location', 'description', 'img', 'password']
        widgets = {
            'password': forms.PasswordInput(),  # Use a password input widget for the password field
        }

# class SignUpForm(forms.Form):
#     username = forms.CharField()
#     email = forms.EmailField()
#     password1 = forms.CharField(widget=forms.PasswordInput)
#     password2 = forms.CharField(widget=forms.PasswordInput)

    

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from .forms import CustomUserCreationForm
from .models import Client
from .models import Client, Company, Product, Sales
from .forms import CompanyForm, ProductForm, SalesForm, ClientForm

def home_index(request):
    return render(request,'myapp/index.html')

def dashboard_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    return render(request,'myapp/dashboard/dashboard.html',  {'username': username, 'sales': sales, 'products': products})

def charts_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    return render(request,'myapp/dashboard/charts.html', {'username': username,'sales': sales, 'products': products})

def tables_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    
    return render(request,'myapp/dashboard/tables.html', {'username': username,'sales': sales, 'products': products})

def insert(request):
    username = request.user.username
    companies = Company.objects.all()
    products = Product.objects.all()
    return render(request, 'myapp/dashboard/insert.html', {'username': username,'companies': companies, 'products': products})

def create_company(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES)
        if form.is_valid():
            company_name = form.cleaned_data['name']

            # Check if a company with the same name already exists
            existing_company = Company.objects.filter(name=company_name).exists()

            if not existing_company:
                form.save()
                messages.success(request, "Company inserted successfully!")
                return redirect('myapp:insert')
            else:
                messages.error(request, "Company with this name already exists.")
    else:
        form = CompanyForm()

    return redirect('myapp:insert')

def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product_name = form.cleaned_data['name']
            product_company_id = form.cleaned_data['c_id'].id  # Assuming the foreign key is named 'company'

            # Check if a product with the same name already exists for the same company
            existing_product = Product.objects.filter(name=product_name, c_id=product_company_id).exists()

            if not existing_product:
                form.save()
                messages.success(request, "Product inserted successfully!")
                return redirect('myapp:insert')  # Redirect to the product list view
            else:
                messages.error(request, "Product with this name already exists for the selected company.")
    else:
        form = ProductForm()

    return redirect('myapp:insert')

def create_sales(request):
    if request.method == 'POST':
        form = SalesForm(request.POST, request.FILES)
        form2 = SalesForm(request.POST)
        if form.is_valid():
                form.save()
                messages.success(request, "Sales inserted successfully!")
                return redirect('myapp:insert') 
    else:
        form = SalesForm()

    return redirect('myapp:insert')

def sign_up(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Create a Client instance and associate it with the user
            Client.objects.create(
                user=user,
                email=user.email,
                password=user.password,
            )

            login(request, user)
            return redirect('/dashboard')
        else:
            print(form.errors)
        
    else:
        form = CustomUserCreationForm()

    return render(request, 'myapp/signup.html', {'form': form})

    # if request.method == 'POST':
    #     form = SignUpForm(request.POST)
    #     if form.is_valid():
    #         username = form.cleaned_data['username']
    #         email = form.cleaned_data['email']
    #         pass1 = form.cleaned_data['password1']
    #         pass2 = form.cleaned_data['password2']

    #         if pass1!=pass2:
    #             messages.success(request, ("Your password doesnot match"))
    #             return redirect('/signup')

    #         my_user = User.objects.create_user(username, email, pass1)

    #         try:
    #             validate_password(pass1, user=my_user)
    #             my_user.save()

    #         except ValidationError as e:
    #             my_user.delete()  # Rollback user creation
    #             messages.error(request, e)
    #             return redirect('/signup')

    #         messages.success(request, ("Account Registered Successfully!"))
    #         return redirect('/login')
    #     else:
    #         messages.error(request, "Form is not valid. Please correct the errors.")
    #         return redirect('/signup')
    # else:
    #     form = SignUpForm()
    # return render(request, 'myapp/signup.html', {'form': form})
# f"Welcome, {user.username}!"

def log_in(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            # messages.success(request, ("Login Successfully!"))
            return redirect('/dashboard')
        else:
            messages.error(request, "Invalid login credentials. Please try again.")
            return render(request, 'myapp/login.html', {'entered_email': email})

    return render(request, 'myapp/login.html')


def log_out(request):
    logout(request)
    return redirect(('/'))

templates/myapp/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>X-Data Solutions | {% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'myapp/css/styles.css' %}"/>      
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'myapp:index' %}">X-Data Solutions</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link {% block nav_home_class %}{% endblock nav_home_class %}" aria-current="page" href="{% url 'myapp:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link {% block nav_about_class %}{% endblock nav_about_class %}" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link {% block nav_services_class %}{% endblock nav_services_class %}" href="#!">Services</a></li>
                        <li class="nav-item"><a class="nav-link {% block nav_contact_class %}{% endblock nav_contact_class %}" href="#!">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right ">
                        <li class="nav-item mx-2">
                            <a class="nav-link text_white {% block nav_login_class %}{% endblock nav_login_class %}" href="{% url 'myapp:login' %}">Login</a>
                        </li>
                        <li class="nav-item mx-2">    
                            <a class="nav-link text_white {% block nav_signup_class %}{% endblock nav_signup_class %}" href="{% url 'myapp:signup' %}">Sign Up</a> 
                        </li>
                     </ul>
                </div>
            </div>
        </nav>    
    {% block main-content %}{% endblock main-content %}
    {% include 'myapp/footer.html' %}      
        <!-- Bootstrap core JS-->    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'myapp/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/myapp/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-5">
        <p class="m-0 text-center text-white">Copyright &copy; X-Data Solutions 2024</p>
    </div>
    <div class="col-md-4">
        <h3>Contact</h3>
        <p>Email: xdatasolutions@gmail.com</p>
        <p>Phone: +977 9000000000</p>
      </div>
</footer>

templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block nav_login_class %}active{% endblock nav_login_class %}

{% block main-content %}

    <div class="container" style="padding-top: 80px;">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card border-0 shadow rounded-3 my-5">
            <div class="card-body p-4 p-sm-5">
              <h5 class="card-title text-center mb-5 fs-5">Login</h5>
              <form action="{% url 'myapp:login' %}" method="post"> 
                {% csrf_token %}
                <div class="form-floating mb-3">
                  <input type="email" class="form-control" id="floatingInputEmail" placeholder="name@example.com" name="email" value="{{ entered_email }}" required>
                  <label for="floatingInputEmail">Email address</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name='password'>
                  <label for="floatingPassword">Password</label>
                </div>
                <div class="space" >
                </div>
                <div class="form-check mb-3">
                  {% comment %} <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck" name='rememberPassword'>
                  <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                  </label> {% endcomment %}
                </div>
                <div class="d-grid">
                  <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit" style="color: #041d36;">Login</button>
                </div>

                <hr class="my-4">
                <a class="d-block text-center mt-2 small" href="{% url 'myapp:signup' %}">Don't have an account? Register Here</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  
{% endblock main-content %}

templates/myapp/signup.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block title %}Sign Up{% endblock title %}

{% block nav_signup_class %}active{% endblock nav_signup_class %}

{% block main-content %}
<div class="container" style="padding-top: 80px;">
  {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    <div class="row">
      <div class="col-lg-10 col-xl-9 mx-auto">
        <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
          <div class="card-body p-4 p-sm-5">
            <h2 class="card-title text-center mb-5 fs-5">Sign Up</h2>
            <form action="" method="post">
              {% csrf_token %}
              <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingInputUsername" placeholder="myusername" name="username" required autofocus>
                <label for="floatingInputUsername">Username</label>
              </div>

              <div class="form-floating mb-3">
                <input type="email" class="form-control" id="floatingInputEmail" placeholder="name@example.com" name="email">
                <label for="floatingInputEmail">Email address</label>
              </div>

              <hr>

              <div class="form-floating mb-3">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password1">
                <label for="floatingPassword">Password</label>
              </div>

              <div class="form-floating mb-3">
                <input type="password" class="form-control" id="floatingPasswordConfirm" placeholder="Confirm Password" name="password2">
                <label for="floatingPasswordConfirm">Confirm Password</label>
              </div>

              <div class="d-grid mb-2">
                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="submit" style="color: #041d36;">Sign Up</button>
              </div>


              <hr class="my-4">

              <a class="d-block text-center mt-2 small" href="{% url 'myapp:login' %}">Have an account? Sign In</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock main-content %}