myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home_index, name='index'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('charts/', views.charts_view, name='charts'),
    path('tables/', views.tables_view, name='tables'),
    path('insert/', views.insert, name='insert'),
    
    path('create_company/', views.create_company, name='create_company'),

    path('create_product/', views.create_product, name='create_product'),
    
    path('create_sales/', views.create_sales, name='create_sales'),

    # path('create_stores/', views.create_stores, name='create_stores'),

]

salesanalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Client(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True, default="default@example.com")
    location = models.CharField(max_length=255)
    description = models.TextField()
    img = models.ImageField(upload_to='images/CustomerProfilePic/', null=True, blank=True)
    password = models.CharField(max_length=255)
     # Add a OneToOneField to associate a Client with a User
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='client')


class Company(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    img = models.ImageField(upload_to='images/ProductPic/', null=True, blank=True)
    quantity = models.IntegerField(default=0)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)

class Client_Product_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Sales(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(auto_now_add=True)
    amount = models.IntegerField(default=0)
    totalprice = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_indivisual = models.BooleanField(default=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)


class Client_Sales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    s_id = models.ForeignKey(Sales, on_delete=models.CASCADE)

class TotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)

class Client_TotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    ts_id = models.ForeignKey(TotalSales, on_delete=models.CASCADE)

class DateTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_DateTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(DateTotalSales, on_delete=models.CASCADE)

class ProductTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_ProductTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(ProductTotalSales, on_delete=models.CASCADE)

class DateProductTotalSales(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True)
    p_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Client_DateProductTotalSales_Bridge(models.Model):
    id = models.AutoField(primary_key=True)
    c_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    dts_id = models.ForeignKey(DateProductTotalSales, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Company, Product, Sales, Client

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'quantity', 'c_id', 'img']



class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        fields = ['amount', 'is_indivisual', 'p_id', 'totalprice']

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'location', 'description', 'img', 'password']
        widgets = {
            'password': forms.PasswordInput(),  # Use a password input widget for the password field
        }

# class SignUpForm(forms.Form):
#     username = forms.CharField()
#     email = forms.EmailField()
#     password1 = forms.CharField(widget=forms.PasswordInput)
#     password2 = forms.CharField(widget=forms.PasswordInput)

    

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from .forms import CustomUserCreationForm
from .models import Client
from .models import Client, Company, Product, Sales
from .forms import CompanyForm, ProductForm, SalesForm, ClientForm

def home_index(request):
    return render(request,'myapp/index.html')

def dashboard_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    return render(request,'myapp/dashboard/dashboard.html',  {'username': username, 'sales': sales, 'products': products})

def charts_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    return render(request,'myapp/dashboard/charts.html', {'username': username,'sales': sales, 'products': products})

def tables_view(request):
    username = request.user.username
    sales = Sales.objects.all()
    products = Product.objects.all()
    
    return render(request,'myapp/dashboard/tables.html', {'username': username,'sales': sales, 'products': products})

def insert(request):
    username = request.user.username
    companies = Company.objects.all()
    products = Product.objects.all()
    return render(request, 'myapp/dashboard/insert.html', {'username': username,'companies': companies, 'products': products})

def create_company(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES)
        if form.is_valid():
            company_name = form.cleaned_data['name']

            # Check if a company with the same name already exists
            existing_company = Company.objects.filter(name=company_name).exists()

            if not existing_company:
                form.save()
                messages.success(request, "Company inserted successfully!")
                return redirect('myapp:insert')
            else:
                messages.error(request, "Company with this name already exists.")
    else:
        form = CompanyForm()

    return redirect('myapp:insert')

def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product_name = form.cleaned_data['name']
            product_company_id = form.cleaned_data['c_id'].id  # Assuming the foreign key is named 'company'

            # Check if a product with the same name already exists for the same company
            existing_product = Product.objects.filter(name=product_name, c_id=product_company_id).exists()

            if not existing_product:
                form.save()
                messages.success(request, "Product inserted successfully!")
                return redirect('myapp:insert')  # Redirect to the product list view
            else:
                messages.error(request, "Product with this name already exists for the selected company.")
    else:
        form = ProductForm()

    return redirect('myapp:insert')

def create_sales(request):
    if request.method == 'POST':
        form = SalesForm(request.POST, request.FILES)
        form2 = SalesForm(request.POST)
        if form.is_valid():
                form.save()
                messages.success(request, "Sales inserted successfully!")
                return redirect('myapp:insert') 
    else:
        form = SalesForm()

    return redirect('myapp:insert')

def sign_up(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Create a Client instance and associate it with the user
            Client.objects.create(
                user=user,
                email=user.email,
                password=user.password,
            )

            login(request, user)
            return redirect('/dashboard')
        else:
            print(form.errors)
        
    else:
        form = CustomUserCreationForm()

    return render(request, 'myapp/signup.html', {'form': form})

    # if request.method == 'POST':
    #     form = SignUpForm(request.POST)
    #     if form.is_valid():
    #         username = form.cleaned_data['username']
    #         email = form.cleaned_data['email']
    #         pass1 = form.cleaned_data['password1']
    #         pass2 = form.cleaned_data['password2']

    #         if pass1!=pass2:
    #             messages.success(request, ("Your password doesnot match"))
    #             return redirect('/signup')

    #         my_user = User.objects.create_user(username, email, pass1)

    #         try:
    #             validate_password(pass1, user=my_user)
    #             my_user.save()

    #         except ValidationError as e:
    #             my_user.delete()  # Rollback user creation
    #             messages.error(request, e)
    #             return redirect('/signup')

    #         messages.success(request, ("Account Registered Successfully!"))
    #         return redirect('/login')
    #     else:
    #         messages.error(request, "Form is not valid. Please correct the errors.")
    #         return redirect('/signup')
    # else:
    #     form = SignUpForm()
    # return render(request, 'myapp/signup.html', {'form': form})
# f"Welcome, {user.username}!"

def log_in(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            # messages.success(request, ("Login Successfully!"))
            return redirect('/dashboard')
        else:
            messages.error(request, "Invalid login credentials. Please try again.")
            return render(request, 'myapp/login.html', {'entered_email': email})

    return render(request, 'myapp/login.html')


def log_out(request):
    logout(request)
    return redirect(('/'))

templates/myapp/dashboard/charts.html
{% extends 'myapp/dashboard/side_base.html' %}
{% load static %}
{% block title %}Charts{% endblock title %}

{% block nav_charts_class %}active{% endblock nav_charts_class %}

{% block main-content %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Charts</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{% url 'myapp:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">Charts</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area me-1"></i>
                Area Chart - Total Sales
            </div>
            <div class="card-body"><canvas id="myAreaChart" width="100%" height="400"></canvas></div>
            
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-chart-bar me-1"></i>
                        Bar Chart - Product Sales
                    </div>
                    <div class="card-body"><canvas id="myBarChart" width="100%" height="200"></canvas></div>
                    
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card mb-4">
                    <!-- <div class="card-header">
                        <i class="fas fa-chart-pie me-1"></i>
                        Pie Chart
                    </div> -->
                    <!-- <div class="card-body"><canvas id="myPieChart" width="100%" height="200"></canvas></div> -->
                   <p></p>
                </div>
            </div>
        </div>
    </div>     
</main>

{% endblock main-content %}

templates/myapp/dashboard/insert.html
{% extends 'myapp/dashboard/side_base.html' %}
{% load static %}
{% block title %}Insert Data{% endblock title %}
{% block nav_insert_class %}active{% endblock nav_insert_class %}

{% block main-content %}
<main>
    <div class="padding" style="padding-left: 10vw; padding-top: 60px; padding-right:10vw; width:80vw;">
        <div class="container mt-1">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
     
        <!-- {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %} -->
        <link rel="stylesheet" href="{% static 'myapp/css/styles.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        
          <form action="{% url 'myapp:create_company' %}" method="post">
         {% csrf_token %}
              <h4>Insert Brand:</h4>
          <div class="mb-3">
        
            <label for="exampleInputEmail1" class="form-label">Name</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="name" aria-describedby="emailHelp">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
         
        </form>
        <br>
        <!-- <hr class="border border-dark border-4 my-4"> -->
        <hr class="border-top border-primary border-4 my-4">
        
        <!-- Product -->
        
        <form action="{% url 'myapp:create_product' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <h4>Insert Product:</h4>
        
          <div class="mb-3">
            <label for="productName" class="form-label">Product Name</label>
            <input type="text" class="form-control" id="productName" name="name" aria-describedby="productNameHelp" required>
          </div>
        
        
          <div class="mb-3">
            <label for="productPrice" class="form-label">Product Price</label>
            <input type="number" class="form-control" id="productPrice" name="price" aria-describedby="productPriceHelp" required>
          </div>
        
          <div class="mb-3">
            <label for="productQuantity" class="form-label">Product Quantity</label>
            <input type="number" class="form-control" id="productQuantity" name="quantity" aria-describedby="productQuantityHelp" required>
          </div>
        
          <div class="mb-3">
            <label for="company" class="form-label">Select Brand</label>
            <select class="form-select" id="company" name="c_id" required>
              <option value="" disabled selected>Select a brand</option>
              {% for company in companies %}
                <option value="{{ company.id }}">{{ company.name }}</option>
              {% endfor %}
            </select>
          </div>
        
          <div class="mb-3">
            <label for="productImage" class="form-label">Product Image</label>
            <input type="file" class="form-control" id="productImage" name="img" accept="image/*" aria-describedby="productImageHelp" required>
          </div>
        
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br>
        <hr class="border-top border-primary border-4 my-4">
        
        <!-- Sales -->
        
        <form action="{% url 'myapp:create_sales' %}" method="post">
          {% csrf_token %}
          <h4>Insert Sales Record:</h4>
        
        
          <div class="mb-3">
            <label for="amount">Sold Quantity:</label>
            <input type="number" class="form-control" id="amount" name="amount" required>
          </div>
        
          <div class="mb-3">
            <label for="totalprice">Total Price:</label>
            <input type="number" class="form-control" id="totalprice" name="totalprice" required>
          </div>
        
          <div class="mb-3">
            <label for="is_indivisual">Is Individual:</label>
            <select class="form-select" id="is_indivisual" name="is_indivisual" required>
              <option value="1" selected>Yes</option>
              <option value="0">No</option>
            </select>
          </div>
        
          <div class="mb-3">
            <label for="product">Product:</label>
            <select class="form-select" id="product" name="p_id" required>
              <option value="" disabled selected>Select a product</option>
              {% for product in products %}
                <option value="{{ product.id }}">{{ product.name }}</option>
              {% endfor %}
            </select>
          </div>
        
        
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <hr class="border-top border-primary border-4 my-4">

</main>

{% endblock main-content %}

templates/myapp/dashboard/tables.html
{% extends 'myapp/dashboard/side_base.html' %}
{% load static %}
{% block title %}Tables{% endblock title %}

{% block nav_tables_class %}active{% endblock nav_tables_class %}

{% block main-content %}
    <main>
        <div class="container-fluid px-4" style="width:80vw">
            <h1 class="mt-4">Tables</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{% url 'myapp:dashboard' %}">Dashboard</a></li>
                <li class="breadcrumb-item active">Tables</li>
            </ol>
            
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                   Products
                </div>
                <div class="card-body">
                  <table id="datatablesSimple" class="table">
                         <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Company</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td>
                                            {% if product.img %}
                                                <img src="{{ product.img.url }}" alt="{{ product.name }}" height="50">
                                            {% else %}
                                                No Image
                                            {% endif %}
                                        </td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.c_id.name }}</td>
                                        
                                    </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                </div>
            </div>

            <br><br>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                   Companies
                </div>
                <div class="card-body">
                  <table id="datatablesSimple" class="table">
                         <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td>
                                            {% if product.img %}
                                                <img src="{{ product.img.url }}" alt="{{ product.name }}" height="50">
                                            {% else %}
                                                No Image
                                            {% endif %}
                                        </td>
                                        <td>{{ product.name }}</td>
                                        
                                    </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                </div>
            </div>
            <br><br>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                  Sales
                </div>
                <div class="card-body">
                  <table id="datatablesSimple" class="table">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Sold Quantity</th>
                                <th>Total Price</th>
                                <th>Is Individual</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Product</th>
                                <th>Sold Quantity</th>
                                <th>Total Price</th>
                                <th>Is Individual</th>
                                <th>Date</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for sale in sales %}
                                <tr><td>
                                        {% if sale.p_id %}
                                            {{ sale.p_id.name }}
                                        {% else %}
                                            No Product
                                        {% endif %}
                                    </td>
                                    <td>{{ sale.amount }}</td>
                                    <td>{{ sale.totalprice }}</td>
                                    <td>{{ sale.is_indivisual }}</td>
                                    <td>{{ sale.date }}</td>
                                   
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


        </div>

    </main>
{% endblock main-content %}